### ISSUE TITLE
issue update from 2.6 to 3.1

### ISSUE THREAD

**Issue by damarteplok** [laravolt/suitable#13]
{!! Suitable::source($articles)
        ->title(__('Artikel'))
        ->columns([
            new \App\Columns\Numbering('No'),
            ['header' => 'Judul', 'field' => 'title', 'sortable' => 'title'],
            ['header' => 'Status', 'field' => 'status', 'sortable' => 'status'],
            ['header' => 'Tanggal', 'field' => 'created_at', 'sortable' => 'created_at'],
            with(new \Laravolt\Suitable\Columns\RestfulButton('artikel'))->only(['edit', 'delete'])
        ])
        ->render() !!}

isue pertama tidak bisa memakai title lagi
isue kedua custom column `Numbering` juga tidak bisa dipakai lagi

**Comment by uyab** [comment]
Fixed in latest version (3.2).
