### ISSUE TITLE
Upgrade ISSUE 

### ISSUE THREAD

**Issue by purwadarozatun** [laravolt/suitable#2]
When upgrade from 2.2.1 to 2.4.1 had one error .

![2017-05-30 14_43_17-welcome ](https://cloud.githubusercontent.com/assets/8139599/26573024/641623d4-4546-11e7-830d-da5a7b12bf75.png)

I think its lot nicer we should keep exsisting variable instead.  To avoid production issue.

**Comment by uyab** [comment]
Thank you for reporting, bug confirmed, will fix it ASAP. Meanwhile, you can modify your custom view :)

**Comment by purwadarozatun** [comment]
Woke .

**Comment by uyab** [comment]
Tagged 2.5.0
